name: trivy
on:
  push:        { branches: [ main ] }
  pull_request:{ branches: [ main ] }

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Trivy FS scan
        uses: aquasecurity/trivy-action@v0.32.0   # ←  update tag
        with:
          scan-type: fs          # scan repository files
          ignore-unfixed: true   # ignore vulns without patch
