name: trivy
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4

      # Scan repository files (no container image needed here)
      - name: Trivy file-system scan
        uses: aquasecurity/trivy-action@v0.18.0
        with:
          scan-type: fs           # file-system scan
          ignore-unfixed: true    # ignore unfixed vulns
          vuln-type: os,library   # scan OS & deps
