name: trivy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Trivy file-system scan
        uses: aquasecurity/trivy-action@v0.32.0
        with:
          scan-type: fs          # scan repository files
          ignore-unfixed: true   # skip vulns with no patch
